### ISSUE TITLE
Application crashes immediately after start (x86_64-linux, release v4)

### ISSUE THREAD

**Issue by kordiangrabowski** [project-gauntlet/gauntlet#11] opened 2024-07-06 13:48 UTC
With no arguments provided application shows unresponsive window then crashes after 2s. 

Application output:
```
./gauntlet
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete

#
# Fatal error in v8_ArrayBuffer_New
# Cannot construct ArrayBuffer with a BackingStore of SharedArrayBuffer
#

Trace/breakpoint trap (core dumped)
```
If `management` argument is passed, application crashes without displaying window: 
```
./gauntlet management
thread 'main' panicked at rust/management_client/src/ui.rs:196:12:
called `Result::unwrap()` on an `Err` value: transport error

Caused by:
    0: error trying to connect: tcp connect error: Connection refused (os error 111)
    1: tcp connect error: Connection refused (os error 111)
    2: Connection refused (os error 111)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 

System details: 
```
Linux 5.15.0-113-generic #123-Ubuntu SMP Mon Jun 10 08:16:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Apple MacBookAir5,2 (board Mac-2E6FAB96566FE58C)
Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
4 GB memory
```

**Comment by Exidex** [comment] 2024-07-07 09:30
Error with `management` (now renamed to `settings`) argument is because the server is not running. I added better error message in UI in [v5](https://github.com/project-gauntlet/gauntlet/releases/tag/v5). 

As for the segfault, it is fixed in the [v5](https://github.com/project-gauntlet/gauntlet/releases/tag/v5). Well, kinda, not really. The issue is only present in cargo `release` mode so for now Gauntlet release will be build in cargo `debug` mode. It is slightly slower and binary size is a lot bigger but at least it works. All this because the Deno version currently used is the only one that works at least in `debug` mode. All other versions fail either with different segfaults (even in `debug` mode) or have some dependency resolution issue.

I will leave this issue open until this is actually fixed. But it may take several months, currently waiting for iced-rs to support wgpu 0.20 (currently uses 0.19) because I am using half a year old Deno version, newer versions use 0.20 and wgpu doesn't support 2 different version at the same time.

**Comment by kordiangrabowski** [comment] 2024-07-07 10:39
V5 works without issues :+1:

**Comment by Exidex** [comment] 2024-08-04 22:05
In V6 instead of using `debug` profile as workaround I am using `opt-level=1` on `release` profile. So the performance is still not as good but at least binary size isn't as bad. Apparently some optimization at  `opt-level=1` is breaking Deno.

**Comment by Exidex** [comment] 2024-09-21 13:21
This is currently blocked by inability to update iced-rs and deno because of wgpu not supporting multiple versions at the same time. Tracked at https://github.com/gfx-rs/wgpu/issues/3105

**Comment by Exidex** [comment] 2024-12-22 14:56
This was an issue in Deno with V8 itself, causing miss-compilation when `opt-level=2` is used. New version of Deno fixed the issue. Gauntlet v12 with Deno update is released. Closing this issue

**Closed by Exidex** 2024-12-22 14:56 UTC
Labels: type: bug, state: waiting-for-upstream, state: waiting-for-release
